import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { TradingCalendar } from '../datafeed/session-calendar';
import type { Maybe, Ohlc } from './math';
import {
  INDICATORS,
  aheadKey,
  defaultParams,
  indicatorById,
  type IndicatorContext,
} from './registry';

/**
 * DR-I1 — the chart's built-in maths against the engine's Pine runtime.
 *
 * `__fixtures__/chart-indicators.reference.json` is generated by the engine
 * (`LascodiaTradingEngine.Scripting.UnitTest/ChartParity`): every built-in of this catalogue written as a Pine
 * script — TradingView's own source where TradingView ships the indicator, otherwise the chart's documented
 * definition (each run's `definition` says which) — run over 360 real EURUSD H1 bars at the catalogue's default
 * inputs, plus variants that pin other inputs. This holds `math.ts` to those values within 1e-9 (relative, floor 1):
 * na where the reference is na, a value where it has one, and the values past the last bar (Ichimoku's cloud, the
 * Alligator) as well.
 *
 * A change to the engine's ta.* or to a reference script fails the engine's test until the fixture is regenerated;
 * the regenerated file copied here fails this test until the maths follows. One definition, two runtimes, no drift.
 */

interface ReferenceRun {
  id: string;
  variant: string | null;
  params: Record<string, number | string>;
  definition: string;
  plots: Record<string, (number | null)[]>;
  future: Record<string, (number | null)[]>;
}

interface Reference {
  session: { session: string; timeZone: string };
  tolerance: number;
  bars: number[][];
  compareBars: number[][];
  runs: ReferenceRun[];
}

// `__dirname` is the spec's own folder under the test runner (jsdom's import.meta.url is not a file URL).
const reference: Reference = JSON.parse(
  readFileSync(join(__dirname, '__fixtures__', 'chart-indicators.reference.json'), 'utf8'),
) as Reference;

const toOhlc = (rows: number[][]): Ohlc[] =>
  rows.map(([time, open, high, low, close, volume]) => ({ time, open, high, low, close, volume }));

const bars = toOhlc(reference.bars);
const compareBars = toOhlc(reference.compareBars);
const calendar = new TradingCalendar(reference.session);
const ctx: IndicatorContext = {
  compareBars,
  tradingDay: calendar.dayOf,
  utcTimes: bars.map((b) => b.time),
  barIntervalMs: 3_600_000,
};

const keyOf = (run: ReferenceRun): string => (run.variant ? `${run.id}:${run.variant}` : run.id);

/** Where one computed series parts from the reference, or null when it matches. */
function divergence(ours: readonly Maybe[], ref: readonly (number | null)[]): string | null {
  const tolerance = reference.tolerance;
  for (let i = 0; i < ref.length; i++) {
    const r = ref[i];
    const o = ours[i] ?? null;
    if (r === null && o === null) continue;
    if (r === null || o === null || !Number.isFinite(o)) {
      return `bar ${i}: reference ${r ?? 'na'}, chart ${o ?? 'na'}`;
    }
    if (Math.abs(o - r) > tolerance * Math.max(1, Math.abs(r))) {
      return `bar ${i}: reference ${r}, chart ${o} (Δ ${(o - r).toExponential(2)})`;
    }
  }
  if (ours.length > ref.length) {
    const extra = ours.slice(ref.length).findIndex((v) => v !== null && v !== undefined);
    if (extra >= 0)
      return `bar ${ref.length + extra}: reference has no bar there, chart ${ours[ref.length + extra]}`;
  }
  return null;
}

describe('built-in indicators match the engine reference (DR-I1)', () => {
  it('covers every built-in of the catalogue', () => {
    const covered = new Set(reference.runs.map((r) => r.id));
    expect(INDICATORS.map((d) => d.id).filter((id) => !covered.has(id))).toEqual([]);
  });

  it('has a reference series for every plot of every built-in', () => {
    const missing: string[] = [];
    for (const run of reference.runs) {
      const def = indicatorById(run.id);
      if (!def) {
        missing.push(`${keyOf(run)}: not in the catalogue`);
        continue;
      }
      for (const plot of def.plots)
        if (!run.plots[plot.key]) missing.push(`${keyOf(run)}.${plot.key}`);
    }
    expect(missing).toEqual([]);
  });

  for (const run of reference.runs) {
    it(`${keyOf(run)} (${run.definition.startsWith('TradingView') ? 'TradingView' : 'chart'} definition)`, () => {
      const def = indicatorById(run.id)!;
      const params = { ...defaultParams(def), ...run.params };
      const computed = def.compute(bars, params, ctx);
      const problems: string[] = [];
      for (const plot of def.plots) {
        const ours = computed[plot.key] ?? [];
        if (ours.length !== bars.length)
          problems.push(`${plot.key}: ${ours.length} values for ${bars.length} bars`);
        const bad = divergence(ours, run.plots[plot.key]);
        if (bad) problems.push(`${plot.key}: ${bad}`);
        const ahead = run.future[plot.key] ?? [];
        const oursAhead = computed[aheadKey(plot.key)] ?? [];
        if (ahead.length || oursAhead.some((v) => v !== null)) {
          const badAhead = divergence(oursAhead, ahead);
          if (badAhead) problems.push(`${plot.key} past the last bar: ${badAhead}`);
        }
      }
      expect(problems, problems.join('\n')).toEqual([]);
    });
  }
});
